### ISSUE TITLE
"show" help text is not shown at the right time

### ISSUE THREAD

**Issue by fredreichbier** [fredreichbier/genie#15]
I missed something in my review of #7, sorry about that! Just noticed that now, the help text with the shortcuts is not printed when the image is displayed, but only after the image window has been closed.
I think your objective was that the help text shouldn't be shown if the given filename is invalid, which I agree to. @Phrohdoh, do you want to take a shot at fixing this? Otherwise I can do it.

**Comment by phrohdoh** [comment]
Yep I'll work on it shortly!
