### ISSUE TITLE
Upscaling in does not work under OS X 10.10.4

### ISSUE THREAD

**Issue by phrohdoh** [fredreichbier/genie#8]
Scaling down works fine with `_` and `-`, but scaling back up with `=` or `+` does not work.
I haven't been able to figure out why yet.

**Comment by fredreichbier** [comment]
Ah, I see you're on OS X, so I guess that answers my question #11 :-) 
Very interesting that there seems to be a conflict between Linux and OS X on the key issue. Maybe we can figure something out that works on both platforms.
